# Generated by Django 3.1.2 on 2021-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('ng_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('sort', models.CharField(choices=[('standard', '楽天標準ソート順'), ('+affiliateRate', 'アフィリエイト料率順(昇順)'), ('-affiliateRate', 'アフィリエイト料率順(降順)'), ('+reviewCount', 'レビュー件数順(昇順)'), ('-reviewCount', 'レビュー件数順(降順)'), ('+itemPrice', '価格順(昇順)'), ('-itemPrice', '価格順(降順)'), ('+reviewAverage', 'レビュー平均順(昇順)'), ('-reviewAverage', 'レビュー平均順(降順)'), ('+updateTimestamp', '商品更新日時順(昇順)'), ('-updateTimestamp', '商品更新日時順(降順)')], max_length=30)),
                ('file', models.CharField(max_length=30)),
                ('folda', models.CharField(max_length=30)),
            ],
        ),
    ]
